version: 0.2
phases:
  install:
    commands:
      - echo Installing Bundler...
      - gem install bundler
      - bundle install --with test
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Preparing database to run tests...
      - RAILS_ENV=test bundle exec rake db:seed
      - RAILS_ENV=test bundle exec rake db:migrate
  build:
    commands:
      - echo Running rubocop check...
      - RAILS_ENV=test rubocop
      - echo Running rspec tests...
      - RAILS_ENV=test bundle exec rspec spec/
