DEFAULTS: &DEFAULTS
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] || 'password' %>

production:
  <<: *DEFAULTS

development:
  <<: *DEFAULTS

test: &test
  <<: *DEFAULTS

staging:
  <<: *DEFAULTS    