DEFAULTS: &DEFAULTS
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] || 'password' %>

production:
  <<: *DEFAULTS
  database: <%= ENV["PRODUCTION_DATABASE"] %>

development:
  <<: *DEFAULTS
  database: <%= ENV["DEVELOPMENT_DATABASE"] %>

test: &test
  <<: *DEFAULTS
  database: <%= ENV["TESTING_DATABASE"] %>  

staging:
  <<: *DEFAULTS
  database: <%= ENV["STAGING_DATABASE"] %>      